services:
  restful-api:
    build:
      dockerfile: restful-api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      collection-service:
        condition: service_started
      postgres:
        condition: service_healthy

  collection-service:
    build:
      dockerfile: collection-service/Dockerfile
    environment:
      - TRANSLATE_API_ADDRESS=${TRANSLATE_API_ADDRESS}
      - TRANSLATE_API_KEY=${TRANSLATE_API_KEY}
    depends_on:
      classification-service:
        condition: service_started
      postgres:
        condition: service_healthy

  classification-service:
    build:
      dockerfile: classification-service/Dockerfile
    environment:
      - CLASSIFICATION_MODEL_NAME=${CLASSIFICATION_MODEL_NAME}
      - GRPC_CLASSIFICATION_SERVICE_HOST=${GRPC_CLASSIFICATION_SERVICE_HOST}
      - GRPC_CLASSIFICATION_SERVICE_PORT=${GRPC_CLASSIFICATION_SERVICE_PORT}

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /home/${USER}/.pgdata:/var/lib/postgresql/data/pgdata
      - ./migrations/data:/etc/postgres/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
