services:
  restful-api:
    build:
      dockerfile: restful-api/Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      collection-service:
        condition: service_started

  collection-service:
    build:
      dockerfile: collection-service/Dockerfile
    env_file: .env
