collection_service:
  host: collection-service
  port: 50051

classification_service:
  host: classification-service
  port: 50052

postgres:
  host: postgres
  port: 5432
  db: coinflow_pg_db
  user: admin
  password: adminpass
