basePath: /v1
definitions:
  models.Transaction:
    properties:
      category:
        type: string
      cost:
        type: number
      description:
        type: string
      target:
        type: string
      type:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      login:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  types.LoginRequestObject:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  types.RefreshRequestObject:
    properties:
      refresh_token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Coinflow API
  version: 0.1.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login and password
        in: body
        name: reqObj
        required: true
        schema:
          $ref: '#/definitions/types.LoginRequestObject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Login and get pair of tokens
      tags:
      - users
  /auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: reqObj
        required: true
        schema:
          $ref: '#/definitions/types.RefreshRequestObject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Refresh and get new pair of tokens
      tags:
      - users
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: reqObj
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Register new user
      tags:
      - users
  /commit:
    post:
      consumes:
      - application/json
      description: Transaction's type and category must be one of allowed values (view
        docs/VARS.md on github for values list).
      parameters:
      - description: Transaction data
        in: body
        name: tx
        required: true
        schema:
          $ref: '#/definitions/models.Transaction'
      - description: Creator id
        in: query
        name: user_id
        required: true
        type: string
      - description: Defines if category should be auto-detected by description (default
          is false)
        in: query
        name: with_auto_category
        type: boolean
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Commit transaction
      tags:
      - transactions
  /summary/categories:
    get:
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      - description: Begin time in RFC3339
        in: query
        name: begin_time
        required: true
        type: string
      - description: End time in RFC3339
        in: query
        name: end_time
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Get summary of transactions for different categories (within time interval)
      tags:
      - summary
  /summary/last-months:
    get:
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      - description: Count of last months (non-negative, optional, default is 1)
        in: query
        name: "n"
        type: string
      - description: Current in RFC3339, optional
        in: query
        name: cur_time
        required: true
        type: string
      - description: Supported timezone (ex. Europe/Moscow, optional, default is UTC)
        in: query
        name: timezone
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Get summary of transactions for last N months
      tags:
      - summary
  /summary/period:
    get:
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      - description: Begin time in RFC3339
        in: query
        name: begin_time
        required: true
        type: string
      - description: End time in RFC3339
        in: query
        name: end_time
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Get summary of transactions within time interval
      tags:
      - summary
  /transaction/id/{tx_id}:
    get:
      description: 'WARNING: Viewing other user''s transactions is not allowed.'
      parameters:
      - description: Transaction ID
        in: path
        name: tx_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Get transaction by id
      tags:
      - transactions
  /transaction/period:
    get:
      consumes:
      - application/json
      description: Time should be presented in RFC3339 format.
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      - description: Begin time in RFC3339 format
        in: query
        name: begin_time
        required: true
        type: string
      - description: End time in RFC3339 format
        in: query
        name: end_time
        required: true
        type: string
      - description: Requested page size (optional, default is 10)
        in: query
        name: page_size
        type: integer
      - description: Last timestamp used in previous page (optional, for keyset pagination)
        in: query
        name: page_token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Get transactions within time interval
      tags:
      - transactions
  /user/{user_id}:
    get:
      description: get user data by id
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: GetUserData
      tags:
      - users
swagger: "2.0"
