// Code generated by MockGen. DO NOT EDIT.
// Source: transactions.go
//
// Generated by this command:
//
//	mockgen -source transactions.go -destination mocks/transactions_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "coinflow/coinflow-server/restful-api/internal/models"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionsRepo is a mock of TransactionsRepo interface.
type MockTransactionsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionsRepoMockRecorder
	isgomock struct{}
}

// MockTransactionsRepoMockRecorder is the mock recorder for MockTransactionsRepo.
type MockTransactionsRepoMockRecorder struct {
	mock *MockTransactionsRepo
}

// NewMockTransactionsRepo creates a new mock instance.
func NewMockTransactionsRepo(ctrl *gomock.Controller) *MockTransactionsRepo {
	mock := &MockTransactionsRepo{ctrl: ctrl}
	mock.recorder = &MockTransactionsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionsRepo) EXPECT() *MockTransactionsRepoMockRecorder {
	return m.recorder
}

// GetTransaction mocks base method.
func (m *MockTransactionsRepo) GetTransaction(txId uuid.UUID) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", txId)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionsRepoMockRecorder) GetTransaction(txId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionsRepo)(nil).GetTransaction), txId)
}

// PostTransaction mocks base method.
func (m *MockTransactionsRepo) PostTransaction(tx *models.Transaction) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostTransaction", tx)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostTransaction indicates an expected call of PostTransaction.
func (mr *MockTransactionsRepoMockRecorder) PostTransaction(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTransaction", reflect.TypeOf((*MockTransactionsRepo)(nil).PostTransaction), tx)
}

// PostTransactionWithoutCategory mocks base method.
func (m *MockTransactionsRepo) PostTransactionWithoutCategory(tx *models.Transaction) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostTransactionWithoutCategory", tx)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostTransactionWithoutCategory indicates an expected call of PostTransactionWithoutCategory.
func (mr *MockTransactionsRepoMockRecorder) PostTransactionWithoutCategory(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTransactionWithoutCategory", reflect.TypeOf((*MockTransactionsRepo)(nil).PostTransactionWithoutCategory), tx)
}
