storage_service:
  host: storage-service
  port: 5051

classification_service:
  host: classification-service
  port: 50052

postgres:
  host: postgres
  port: 5432
  db: coinflow_pg_db
  user: admin
  password: adminpass

service:
  do_translate: true
  category_chan_buffer: 128
  category_timeout: 5m
  http_code_header_name: x-http-code
