auth_service:
  host: auth-service
  port: 5053

postgres:
  host: postgres
  port: 5432
  db: coinflow_pg_db
  user: admin
  password: adminpass

redis:
  host: redis
  port: 6379
  user: admin
  user_password: adminpass
  db_number: 0

jwt:
  issuer: coinflow-server.auth-service
  access_expiration_time: 30m
  refresh_expiration_time: 168h

service:
  auth_cookie_name: accessToken
  http_code_header_name: x-http-code
