name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: private-env
    env:
      TRANSLATE_API_ADDRESS: ${{ secrets.TRANSLATE_API_ADDRESS }}
      TRANSLATE_API_KEY: ${{ secrets.TRANSLATE_API_KEY }}
      PRIVATE_KEY_PEM: ${{ secrets.PRIVATE_KEY_PEM }}
      PUBLIC_KEY_PEM: ${{ secrets.PUBLIC_KEY_PEM }}
      AUTH_JWKS: ${{ secrets.AUTH_JWKS }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Make
      run: sudo apt install make

    - name: Build and Test
      run: |
        mv public.env .env
        make launch_services_with_tests

    - name: Shut Down Docker Compose
      if: always()
      run: make stop_services
