name: Docker Compose CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: private-env
    env:
      TRANSLATE_API_ADDRESS: ${{ secrets.TRANSLATE_API_ADDRESS }}
      TRANSLATE_API_KEY: ${{ secrets.TRANSLATE_API_KEY }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Make
      run: sudo apt install make

    - name: Build and Test
      run: |
        mv public.env .env
        echo "TRANSLATE_API_ADDRESS=$TRANSLATE_API_ADDRESS" >> .env
        echo "TRANSLATE_API_KEY=$TRANSLATE_API_KEY" >> .env
        echo "JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY" >> .env
        echo "JWT_PUBLIC_KEY=$JWT_PUBLIC_KEY" >> .env
        make launch_services_with_tests

    - name: Shut Down Docker Compose
      if: always()
      run: make stop_services
